repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: no-go-testing
      - id: golangci-lint
      - id: go-unit-tests
      - id: go-mod-tidy
      - id: validate-toml

  - repo: local
    hooks:
      - id: local-templ-fmt
        name: templ fmt
        entry: templ fmt
        language: system
        types: [text]
        files: "\\.templ$" 

      - id: local-biome-check
        name: biome check
        entry: npx biome check --apply --files-ignore-unknown=true --no-errors-on-unmatched ./src
        language: system
        types: [text]
        files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?|css)$"

      - id: local-jasmine-test
        name: npx jasmine 
        entry: npx jasmine
        language: node
        pass_filenames: false

      - id: local-playwright-test
        name: npx playwright test
        entry: npx playwright test
        language: node
        pass_filenames: false

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.16.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
