services:
  app:
    image: gavink97/app:latest
    build:
      context: .
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    environment:
      - env=prod
    ports:
      - 80:8080
    expose:
      - 8080
    volumes:
      - .env:/.env
      - ./users.db:/users.db
